# Generated by Django 2.2.5 on 2019-10-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountFollowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('profile_pic_url', models.CharField(default='', max_length=512)),
                ('month_now', models.IntegerField(blank=True, null=True)),
                ('month_prev', models.IntegerField(blank=True, null=True)),
                ('month_diff', models.IntegerField(blank=True, null=True)),
                ('today', models.IntegerField(blank=True, null=True)),
                ('today_diff', models.IntegerField(blank=True, null=True)),
                ('prev_one', models.IntegerField(blank=True, null=True)),
                ('prev_one_diff', models.IntegerField(blank=True, null=True)),
                ('prev_two', models.IntegerField(blank=True, null=True)),
                ('prev_two_diff', models.IntegerField(blank=True, null=True)),
                ('prev_three', models.IntegerField(blank=True, null=True)),
                ('prev_three_diff', models.IntegerField(blank=True, null=True)),
                ('prev_four', models.IntegerField(blank=True, null=True)),
                ('prev_four_diff', models.IntegerField(blank=True, null=True)),
                ('prev_five', models.IntegerField(blank=True, null=True)),
                ('prev_five_diff', models.IntegerField(blank=True, null=True)),
                ('prev_six', models.IntegerField(blank=True, null=True)),
                ('prev_six_diff', models.IntegerField(blank=True, null=True)),
                ('prev_seven', models.IntegerField(blank=True, null=True)),
                ('prev_seven_diff', models.IntegerField(blank=True, null=True)),
                ('prev_eight', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountFollows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('profile_pic_url', models.CharField(default='', max_length=512)),
                ('month_now', models.IntegerField(blank=True, null=True)),
                ('month_prev', models.IntegerField(blank=True, null=True)),
                ('month_diff', models.IntegerField(blank=True, null=True)),
                ('today', models.IntegerField(blank=True, null=True)),
                ('today_diff', models.IntegerField(blank=True, null=True)),
                ('prev_one', models.IntegerField(blank=True, null=True)),
                ('prev_one_diff', models.IntegerField(blank=True, null=True)),
                ('prev_two', models.IntegerField(blank=True, null=True)),
                ('prev_two_diff', models.IntegerField(blank=True, null=True)),
                ('prev_three', models.IntegerField(blank=True, null=True)),
                ('prev_three_diff', models.IntegerField(blank=True, null=True)),
                ('prev_four', models.IntegerField(blank=True, null=True)),
                ('prev_four_diff', models.IntegerField(blank=True, null=True)),
                ('prev_five', models.IntegerField(blank=True, null=True)),
                ('prev_five_diff', models.IntegerField(blank=True, null=True)),
                ('prev_six', models.IntegerField(blank=True, null=True)),
                ('prev_six_diff', models.IntegerField(blank=True, null=True)),
                ('prev_seven', models.IntegerField(blank=True, null=True)),
                ('prev_seven_diff', models.IntegerField(blank=True, null=True)),
                ('prev_eight', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('profile_pic_url', models.CharField(default='', max_length=512)),
                ('scrape_date', models.DateField()),
                ('posts', models.IntegerField(default=0)),
                ('followers', models.IntegerField(default=0)),
                ('follows', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='accountsummary',
            index=models.Index(fields=['posts'], name='dashboard_a_posts_eeaa1e_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsummary',
            index=models.Index(fields=['followers'], name='dashboard_a_followe_2fc62c_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsummary',
            index=models.Index(fields=['follows'], name='dashboard_a_follows_23f3d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accountsummary',
            unique_together={('account_name', 'scrape_date')},
        ),
        migrations.AddIndex(
            model_name='accountfollows',
            index=models.Index(fields=['account_name'], name='dashboard_a_account_d211d1_idx'),
        ),
        migrations.AddIndex(
            model_name='accountfollows',
            index=models.Index(fields=['month_now'], name='dashboard_a_month_n_4b4372_idx'),
        ),
        migrations.AddIndex(
            model_name='accountfollows',
            index=models.Index(fields=['today'], name='dashboard_a_today_39b462_idx'),
        ),
        migrations.AddIndex(
            model_name='accountfollows',
            index=models.Index(fields=['prev_one'], name='dashboard_a_prev_on_13c4ca_idx'),
        ),
        migrations.AddIndex(
            model_name='accountfollows',
            index=models.Index(fields=['prev_two'], name='dashboard_a_prev_tw_b5aca8_idx'),
        ),
        migrations.AddIndex(
            model_name='accountfollows',
            index=models.Index(fields=['prev_three'], name='dashboard_a_prev_th_56f3aa_idx'),
        ),
        migrations.AddIndex(
            model_name='accountfollows',
            index=models.Index(fields=['prev_four'], name='dashboard_a_prev_fo_478257_idx'),
        ),
        migrations.AddIndex(
            model_name='accountfollows',
            index=models.Index(fields=['prev_five'], name='dashboard_a_prev_fi_9af18b_idx'),
        ),
        migrations.AddIndex(
            model_name='accountfollows',
            index=models.Index(fields=['prev_six'], name='dashboard_a_prev_si_5b78ed_idx'),
        ),
        migrations.AddIndex(
            model_name='accountfollows',
            index=models.Index(fields=['prev_seven'], name='dashboard_a_prev_se_57835a_idx'),
        ),
        migrations.AddIndex(
            model_name='accountfollowers',
            index=models.Index(fields=['account_name'], name='dashboard_a_account_8461a8_idx'),
        ),
        migrations.AddIndex(
            model_name='accountfollowers',
            index=models.Index(fields=['month_now'], name='dashboard_a_month_n_c62c56_idx'),
        ),
        migrations.AddIndex(
            model_name='accountfollowers',
            index=models.Index(fields=['today'], name='dashboard_a_today_a0b49f_idx'),
        ),
        migrations.AddIndex(
            model_name='accountfollowers',
            index=models.Index(fields=['prev_one'], name='dashboard_a_prev_on_79e2b5_idx'),
        ),
        migrations.AddIndex(
            model_name='accountfollowers',
            index=models.Index(fields=['prev_two'], name='dashboard_a_prev_tw_6852b5_idx'),
        ),
        migrations.AddIndex(
            model_name='accountfollowers',
            index=models.Index(fields=['prev_three'], name='dashboard_a_prev_th_81986c_idx'),
        ),
        migrations.AddIndex(
            model_name='accountfollowers',
            index=models.Index(fields=['prev_four'], name='dashboard_a_prev_fo_d9abc1_idx'),
        ),
        migrations.AddIndex(
            model_name='accountfollowers',
            index=models.Index(fields=['prev_five'], name='dashboard_a_prev_fi_463be9_idx'),
        ),
        migrations.AddIndex(
            model_name='accountfollowers',
            index=models.Index(fields=['prev_six'], name='dashboard_a_prev_si_504f34_idx'),
        ),
        migrations.AddIndex(
            model_name='accountfollowers',
            index=models.Index(fields=['prev_seven'], name='dashboard_a_prev_se_29468b_idx'),
        ),
    ]
