# Generated by Django 2.2.5 on 2019-10-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='account_summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('account_name', models.CharField(max_length=100)),
                ('posts', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('follows', models.IntegerField()),
                ('scrape_date', models.DateField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='account',
        ),
        migrations.DeleteModel(
            name='follow',
        ),
        migrations.DeleteModel(
            name='follower',
        ),
    ]
