# Generated by Django 2.2.5 on 2019-10-14 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20191014_0904'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account_summary',
            unique_together={('user_id', 'account_name', 'scrape_date')},
        ),
    ]
