# Generated by Django 2.2.5 on 2019-10-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20191014_0913'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account_summary',
            index=models.Index(fields=['user_id'], name='dashboard_a_user_id_98a346_idx'),
        ),
        migrations.AddIndex(
            model_name='account_summary',
            index=models.Index(fields=['account_name'], name='dashboard_a_account_b37e86_idx'),
        ),
        migrations.AddIndex(
            model_name='account_summary',
            index=models.Index(fields=['scrape_date'], name='dashboard_a_scrape__f0581a_idx'),
        ),
    ]
