# Generated by Django 2.2.5 on 2019-10-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20191014_0918'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='account_summary',
            name='dashboard_a_user_id_98a346_idx',
        ),
        migrations.RemoveIndex(
            model_name='account_summary',
            name='dashboard_a_account_b37e86_idx',
        ),
        migrations.RemoveIndex(
            model_name='account_summary',
            name='dashboard_a_scrape__f0581a_idx',
        ),
        migrations.AddIndex(
            model_name='account_summary',
            index=models.Index(fields=['posts'], name='dashboard_a_posts_b4a43a_idx'),
        ),
        migrations.AddIndex(
            model_name='account_summary',
            index=models.Index(fields=['followers'], name='dashboard_a_followe_12ec4c_idx'),
        ),
        migrations.AddIndex(
            model_name='account_summary',
            index=models.Index(fields=['follows'], name='dashboard_a_follows_06764b_idx'),
        ),
    ]
