# Generated by Django 2.2.5 on 2019-10-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20191014_0919'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='account_summary',
            new_name='AccountSummary',
        ),
        migrations.RemoveIndex(
            model_name='accountsummary',
            name='dashboard_a_posts_b4a43a_idx',
        ),
        migrations.RemoveIndex(
            model_name='accountsummary',
            name='dashboard_a_followe_12ec4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='accountsummary',
            name='dashboard_a_follows_06764b_idx',
        ),
        migrations.AddIndex(
            model_name='accountsummary',
            index=models.Index(fields=['posts'], name='dashboard_a_posts_eeaa1e_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsummary',
            index=models.Index(fields=['followers'], name='dashboard_a_followe_2fc62c_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsummary',
            index=models.Index(fields=['follows'], name='dashboard_a_follows_23f3d3_idx'),
        ),
    ]
